# Generated by Django 5.0.6 on 2024-08-19 13:45

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('phone_number', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Phone number must be in the format 09XXXXXXXX', regex='^09\\d{8}$')])),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('pharmacist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_the_week', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thr', 'Thirsday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=3)),
                ('opened_at', models.TimeField(blank=True, null=True)),
                ('closed_at', models.TimeField(blank=True, null=True)),
                ('pharmacies', models.ManyToManyField(related_name='business_hours', to='APIs.pharmacy')),
            ],
        ),
        migrations.AddConstraint(
            model_name='businesshours',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('opened_at__isnull', True), ('closed_at__isnull', True)), ('opened_at__lt', models.F('closed_at')), _connector='OR'), name='opened_at_is_lt_closed_at'),
        ),
        migrations.AlterUniqueTogether(
            name='businesshours',
            unique_together={('day_of_the_week', 'opened_at', 'closed_at')},
        ),
    ]
